# Generated by Django 4.1.7 on 2023-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ranking',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
