# Generated by Django 4.1.7 on 2023-03-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_alter_team_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ranking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='win_percentage',
            field=models.FloatField(default=0),
        ),
    ]
