# Generated by Django 4.1.7 on 2023-03-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_team_ranking_alter_team_win_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brolympic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.brolympics', verbose_name='brolympic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='team',
            name='brolympic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.brolympics', verbose_name='brolympic'),
        ),
    ]
