# Generated by Django 4.1.7 on 2023-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_event_brolympic_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='low_score_wins',
            field=models.BooleanField(default=False),
        ),
    ]
