# Generated by Django 4.1.7 on 2023-03-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_eventteamranking_h2h_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions_h2h',
            name='low_score_wins',
        ),
        migrations.RemoveField(
            model_name='competitions_score',
            name='low_score_wins',
        ),
    ]
