# Generated by Django 4.1.7 on 2023-03-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_competitions_h2h_low_score_wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions_score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions_team', to='competition.team'),
        ),
    ]
