# Generated by Django 4.1.7 on 2023-03-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_alter_competitions_score_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions_h2h',
            name='team_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitions_h2h',
            name='team_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitions_h2h',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='competition.team'),
        ),
        migrations.AlterField(
            model_name='competitions_score',
            name='player_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitions_score',
            name='player_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitions_score',
            name='team_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='brolympic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.brolympics', verbose_name='brolympic'),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='win_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_h2h',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_score',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventteamranking_score',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventteamranking_score',
            name='team_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='brolympic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.brolympics', verbose_name='brolympic'),
        ),
    ]
