# Generated by Django 4.1.7 on 2023-03-07 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_alter_eventteamranking_h2h_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventteamranking_score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_event_ranking_score', to='competition.team'),
        ),
    ]
